# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Lint and test code"
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build_container:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: riptidecr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build docker image
        run: docker build . -t riptidecr.azurecr.io/finances:latest
      - name: Publish image
        run: docker push riptidecr.azurecr.io/finances:latest

      - name: Setup cloudflared client
        run: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Configure cloudflared ssh
        run : echo -e "Host ssh-finances.bosswatchtower.com\nProxyCommand /usr/bin/cloudflared access ssh --hostname %h" > ~/.ssh/config

      - name: Stop current nomad job
        run: ssh root@ssh-finances.bosswatchtower.com 'nomad stop --purge finances'
        continue-on-error: true

      - name: Run Nomad job
        run: ssh root@ssh-finances.bosswatchtower.com 'nomad run /opt/jobs/finances.hcl'
